# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build server binaries

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    branches: [ "main" ]
    paths:
      - "server/*.go"
  pull_request:
    branches: [ "main" ]
    paths:
      - "server/*.go"
  workflow_dispatch:

jobs:
  build-go-binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64, arm64]
        exclude: # exclude some OSs and architectures
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.30
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # a pre-defined secret to add files to Release
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.22 # the required Go version
          binary_name: "server" # the name of the binary executable
          extra_files: README.md # the extra files to add to the release
