# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build server binaries

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    branches: [ "main" ]
    paths:
      - "server/*.go"
  pull_request:
    branches: [ "main" ]
    paths:
      - "server/*.go"
  workflow_dispatch:

jobs:
  build-go-binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.0' # The Go version to download (if necessary) and use.
      - name: Build server binaries
        working-directory: ./server
        run: >
          cd server/ && GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }}
          go build -o net-transfer-server_${{ matrix.goos }}-${{ matrix.goarch }} .
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            net-transfer-server_${{ matrix.goos }}-${{ matrix.goarch }}